name: Bump Version

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true
          force-bump-patch-version: true
          prerelease: ${{ github.event_name == 'pull_request' }}
          changelog-file: CHANGELOG.md
      - name: Set up Git
        if: steps.semrel.outputs.version != ''
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Commit
        if: steps.semrel.outputs.version != ''
        run: |
          sed -i -r 's@(appVersion: "v)[0-9]+\.[0-9]+\.[0-9]+[^ ]*(")@\1${{ steps.semrel.outputs.version }}\2@g' deploy/cloudeventscheduler/Chart.yaml
          echo '{{ steps.semrel.outputs.version }}' > .version
          git add .version CHANGELOG.md deploy/cloudeventscheduler/Chart.yaml
          git commit -m "chore(release): Bump version to ${{ steps.semrel.outputs.version }}"
      - name: Push to master
        if: steps.semrel.outputs.version != '' && github.event_name == 'push'
        run: |
          git push origin master
      - name: Update major tag
        if: steps.semrel.outputs.version != ''
        run: |
          TAG=v${{ steps.semrel.outputs.version_major }}
          git push origin :refs/tags/${TAG}
          git tag -fa ${TAG} -m "Release v${{ steps.semrel.outputs.version }}"
          git push origin ${TAG}
      - name: Update minor tag
        if: steps.semrel.outputs.version != ''
        run: |
          TAG=v${{ steps.semrel.outputs.version_major }}.${{ steps.semrel.outputs.version_minor }}
          git push origin :refs/tags/${TAG}
          git tag -fa ${TAG} -m "Release v${{ steps.semrel.outputs.version }}"
          git push origin ${TAG}
